repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: no-commit-to-branch
      - id: pretty-format-json
        exclude: Pipfile.lock
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
      - id: flake8
  - repo: https://github.com/hukkinj1/mdformat
    rev: 0.1.1
    hooks:
      - id: mdformat
