version: '3'

services:
  db:
    image: kartoza/postgis:11.0-2.5
    ports:
      - "5432:5432"
    volumes:
      - "wazimap-data:/var/lib/postgresql/"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,pg_trgm
    stop_grace_period: 60s
    container_name: wazimap-ng_db_1
  web:
    image: adieyal/wazimap-ng:latest
    depends_on:
     - db
    ports:
      - "8000:8000"
    env_file:
      - ./config/django/django.env
    volumes:
      - ./:/app/
      - ./scripts:/scripts/
    container_name: wazimap-ng_web_1
volumes:
  wazimap-data:
