version: '3'

services:
  db:
    image: kartoza/postgis:12.0
    ports:
      - "5432:5432"
    volumes:
      - "wazimap-data:/var/lib/postgresql/"
    environment:
      - POSTGRES_DBNAME=wazimap_ng
      - POSTGRES_USER=wazimap_ng
      - POSTGRES_PASS=wazimap_ng
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,pg_trgm
    stop_grace_period: 60s
    container_name: wazimap-ng_db_1
  web:
    image: adieyal/wazimap-ng:staging
    depends_on:
     - db
    ports:
      - "8000:8000"
    env_file:
      - ./config/django/django.env
    volumes:
      - ./:/app/
      - ./scripts:/scripts/
    container_name: wazimap-ng_web_1
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DEFAULT_FILE_STORAGE
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
      - DATABASE_URL
      - DJANGO_CONFIGURATION
volumes:
  wazimap-data:
