#!/bin/bash

python manage.py loadshp --create-hierarchy ./datasets/shapefiles/africa-outline/africa-outline.shp REGION=name,code=code,PTR=parent_code,Shape_Area=area Africa Continent Climate
python manage.py loadshp "./datasets/shapefiles/generated/africa-countries/features.shp" COUNTRY=name,GID_0=code,parent_cod=parent_code,area=area Africa Country Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Tunisia/Tunisia/Governorate/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Governorate" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Zimbabwe/Zimbabwe/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Zimbabwe/Zimbabwe/City/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "City" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Zambia/Zambia/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Togo/Togo/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/SouthSudan/SouthSudan-Regions/State/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "State" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Swaziland/Swaziland/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Sudan/Sudan-Regions/State/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "State" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Tanzania/Tanzania-Regions/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/SouthAfrica/SouthAfrica/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Seychelles/Seychelles/OuterIslands/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "OuterIslands" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Seychelles/Seychelles/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Sierra-Leone/Sierra-Leone/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Somalia/Somalia/Region/features.shp" NAME=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Senegal/Senegal/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Nigeria/Nigeria/State/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "State" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Niger/Niger/Department/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Department" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Niger/Niger/CapitalDistrict/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "CapitalDistrict" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Rwanda/Rwanda-Regions/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Namibia/Namibia/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Morocco/Morocco/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mozambique/Mozambique/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mauritius/Mauritius/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mauritius/Mauritius/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mauritius/Mauritius/Autonomousisland/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Autonomousisland" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mali/Mali/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mali/Mali/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mauritania/Mauritania/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Mauritania/Mauritania/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Libya/Libya/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Liberia/Liberia/County/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "County" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Lesotho/Lesotho/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Kenya/Kenya/County/features.shp" NAME=name,code=code,parent_cod=parent_code,area=area Africa "County" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Guinea/Guinea/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Guinea-Bissau/Guinea-Bissau/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Guinea-Bissau/Guinea-Bissau/AutonomousSector/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "AutonomousSector" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/IvoryCoast/IvoryCoast/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/IvoryCoast/IvoryCoast/Autonomousdistrict/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Autonomousdistrict" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Ghana/Ghana/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Gabon/Gabon/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Gambia/Gambia/IndependentCity/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "IndependentCity" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Gambia/Gambia/Division/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Division" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Ethiopia/Ethiopia/State/features.shp" NAME=name,code=code,parent_cod=parent_code,area=area Africa "State" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Ethiopia/Ethiopia/City/features.shp" NAME=name,code=code,parent_cod=parent_code,area=area Africa "City" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Eritrea/Eritrea/Region/features.shp" NAME=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Egypt/Egypt/Governorate/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Governorate" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Djibouti/Djibouti-Regions/Region/features.shp" NAME=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/EquatorialGuinea/EquatorialGuinea/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/DRC/DRC/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Congo/Congo/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Chad/Chad/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Comoros/Comoros/AutonomousIsland/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "AutonomousIsland" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/CentralAfricaRepublic/CentralAfricaRepublic/Prefecture/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Prefecture" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/CentralAfricaRepublic/CentralAfricaRepublic/EconomicPrefecture/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "EconomicPrefecture" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/CentralAfricaRepublic/CentralAfricaRepublic/AutonomousCommune/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "AutonomousCommune" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Cameroon/Cameroon/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Burundi/Burundi-Regions/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/CapeVerde/CapeVerde/County/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "County" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Bukina Faso/Bukina-Faso/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Botswana/Botswana/Town/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Town" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Botswana/Botswana/District/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "District" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Botswana/Botswana/City/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "City" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Angola/Angola/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Benin/Benin/Department/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Department" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Algeria/Algeria/Province/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Province" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Malawi/modified/Malawi-Regions/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
python manage.py loadshp "./datasets/shapefiles/generated/countries-regions/Madagascar/modified/Madagascar-Regions/Region/features.shp" Name=name,code=code,parent_cod=parent_code,area=area Africa "Region" Climate
