# Generated by Django 2.2.24 on 2022-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0052_auto_20220111_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofilehighlight',
            name='display_format',
            field=models.CharField(choices=[('absolute_value', 'Integer'), ('decimal', 'Decimal'), ('percentage', 'Percentage')], default='percentage', help_text='Method for displaying the value to the user.', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalprofilekeymetrics',
            name='display_format',
            field=models.CharField(choices=[('absolute_value', 'Integer'), ('decimal', 'Decimal'), ('percentage', 'Percentage')], default='percentage', help_text='Method for displaying the value to the user.', max_length=32),
        ),
        migrations.AddField(
            model_name='profilehighlight',
            name='display_format',
            field=models.CharField(choices=[('absolute_value', 'Integer'), ('decimal', 'Decimal'), ('percentage', 'Percentage')], default='percentage', help_text='Method for displaying the value to the user.', max_length=32),
        ),
        migrations.AddField(
            model_name='profilekeymetrics',
            name='display_format',
            field=models.CharField(choices=[('absolute_value', 'Integer'), ('decimal', 'Decimal'), ('percentage', 'Percentage')], default='percentage', help_text='Method for displaying the value to the user.', max_length=32),
        ),
    ]
