# Generated by Django 2.2.28 on 2024-10-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0053_value_display_format'),
        ('profile', '0055_auto_20220929_1453'),
    ]

    operations = [
    ]
