name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose run --rm web scripts/wait-for-postgres.sh
      - name: Run tests
        run: docker-compose run --rm -e DJANGO_CONFIGURATION=Test web pytest /app/tests
      - name: Start server
        run: docker-compose up -d
      - name: "Smoke test: Check that demo data is returned by typical request to server"
        run: wget --retry-connrefused --waitretry=1 --read-timeout=10 --timeout=10 --tries=10 -O-  "http://localhost:8000/api/v1/datasets" | grep "results"

